# Generated by Django 3.2.25 on 2024-12-17 05:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_studentdetails_roll_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='joining_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
